Repository TinU-Official/TinU-Client, pull requests merged in 2024-11, with the labels that each got.

#14 init: font 및 theme을 세팅합니다.
  index.html
  src/App.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
Labels: ⚙️ init, size/L

#21 feat: 공통 TextField 컴포넌트를 구현합니다.
  .gitignore
  .storybook/main.ts
  .storybook/preview-head.html
  .storybook/preview.tsx
  package.json
  src/components/Common/TextField/TextField.stories.tsx
  src/components/Common/TextField/TextField.tsx
  src/styles/theme.ts
  yarn.lock
Labels: ✨ feat, size/XXL

#23 test: jira & github 연동
  package.json
  yarn.lock
Labels: size/XS

#29 TINU-81 feat: Docker CI/CD 파이프라인을 구축합니다.
  .github/workflows/deploy.yml
  Dockerfile
  src/pages/Home.tsx
Labels: ✨ feat, size/M

#30 init: commitlint 세팅을 진행합니다.
  .husky/_/prepare-commit-msg
  .husky/commit-msg
  commitlint.config.js
  package.json
  yarn.lock
Labels: ⚙️ init, size/XL

#33 TINU-82 chore: yarn berry 마이그레이션을 진행합니다.
  .gitignore
  .vscode/extensions.json
  .yarn/releases/yarn-4.5.3.cjs
  .yarn/sdks/eslint/bin/eslint.js
  .yarn/sdks/eslint/lib/api.js
  .yarn/sdks/eslint/lib/unsupported-api.js
  .yarn/sdks/eslint/package.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/prettier/bin/prettier.cjs
  .yarn/sdks/prettier/index.cjs
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/tsserverlibrary.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  Dockerfile
  package.json
  yarn.lock
Labels: size/XXL, 📦 chore
