Repository TinU-Official/TinU-Client, pull requests merged in 2024-09, with the labels that each got.

#4 init: Router 초기세팅을 진행합니다.
  package.json
  src/App.tsx
  src/Router.tsx
  src/components/Home/.gitkeep
  src/main.tsx
  src/pages/Home.tsx
  yarn.lock
Labels: ⚙️ init

#7 init: ky 라이브러리 세팅
  package-lock.json
  package.json
  src/libs/api.ts
  yarn.lock
Labels: ⚙️ init

#9 init: GlobalStyle 세팅
  package.json
  src/styles/GlobalStyles.ts
  yarn.lock
Labels: ⚙️ init, size/XL

#10 init: react-query 초기 세팅을 진행합니다.
  package.json
  src/App.tsx
  src/Router.tsx
  yarn.lock
Labels: ⚙️ init, size/M
