Repository TinU-Official/TinU-Client, pull requests merged in 2025-05, with the labels that each got.

#88 feat: 채팅 리스트 페이지 구현
  public/img_dummy.png
  src/app/(with-navbar)/(with-logo-header)/chat-list/chatList.css.ts
  src/app/(with-navbar)/(with-logo-header)/chat-list/page.tsx
  src/app/(with-navbar)/(with-logo-header)/layout.tsx
  src/app/(with-navbar)/layout.tsx
  src/assets/icons/ic_chat_grey.svg
  src/assets/icons/ic_chat_mint.svg
  src/assets/icons/ic_hamburger.svg
  src/assets/icons/ic_home_grey.svg
  src/assets/icons/ic_home_mint.svg
  src/assets/icons/ic_user_grey.svg
  src/assets/imgs/img_chat_empty.svg
  src/assets/imgs/img_logo_small.svg
  src/components/ChatList/ChatListItem/ChatListItem.tsx
  src/components/ChatList/ChatListItem/chatListItem.css.ts
  src/components/ChatList/FilterButton/FilterButton.tsx
  src/components/ChatList/FilterButton/filterButton.css.ts
  src/components/Common/NavBar/NavBar.tsx
  src/components/Common/NavBar/navBar.css.ts
  src/types/chatListTypes.ts
Labels: ✨ feat, size/XL

#87 feat: 채팅 화면 페이지 구현
  public/sechon.png
  src/app/chat/chat.css.ts
  src/app/chat/page.tsx
  src/app/layout.tsx
  src/assets/icons/ic_airplane_grey.svg
  src/assets/icons/ic_airplane_mint.svg
  src/assets/icons/ic_camera.svg
  src/assets/icons/ic_more_vertical.svg
  src/assets/icons/ic_plus.svg
  src/assets/imgs/img_mock.png
  src/components/Chat/ChatBottomSheet/ChatBottomSheet.tsx
  src/components/Chat/ChatBottomSheet/chatBottomSheet.css.ts
  src/components/Chat/ChatScreen/ChatScreen.tsx
  src/components/Chat/ChatScreen/chatScreen.css.ts
  src/components/Chat/DailyChatGroup/DailyChatGroup.tsx
  src/components/Chat/DailyChatGroup/dailyChatGroup.css.ts
  src/components/Chat/MoreButton/MoreButton.tsx
  src/components/Chat/ProductInfo/ProductInfo.tsx
  src/components/Chat/ProductInfo/productInfo.css.ts
  src/components/Chat/ReceiverChatBubble/ReceiverChatBubble.tsx
  src/components/Chat/ReceiverChatBubble/receiverChatBubble.css.ts
  src/components/Chat/SenderChatBubble/SenderChatBubble.tsx
  src/components/Chat/SenderChatBubble/senderChatBubble.css.ts
  src/components/Common/BackButton/BackButton.tsx
  src/hooks/Chat/useScrollToBottom.ts
  src/styles/global.css.ts
Labels: ✨ feat, size/XL

#93 feat: Select 컴포넌트 구현
  src/assets/icons/ic_chevron_down.svg
  src/assets/icons/ic_chevron_up.svg
  src/components/Common/Select/Select.css.ts
  src/components/Common/Select/Select.tsx
Labels: size/L

#95 feat: step4 - [회원가입] 추가정보 입력 페이지
  src/app/sign-up/univ/page.tsx
  src/app/sign-up/univ/univ.css.ts
  src/assets/icons/ic_swap.svg
  src/components/SignUp/Terms/TermsForm/termsForm.css.ts
  src/components/SignUp/Univ/UnivInfoForm.css.ts
  src/components/SignUp/Univ/UnivInfoForm.tsx
Labels: ✨ feat, size/L
