Repository TinU-Official/TinU-Client, pull requests merged in 2025-02, with the labels that each got.

#44 TINU-77 feat: Step1 컴포넌트 구현
  package.json
  src/Router.tsx
  src/assets/index.ts
  src/assets/svg/check/ic_check-complete.svg
  src/assets/svg/check/ic_check-grey.svg
  src/assets/svg/check/ic_check-mint.svg
  src/assets/svg/check/ic_check-transparent.svg
  src/assets/svg/check/ic_check-whitegrey.svg
  src/assets/svg/ic_back.svg
  src/assets/svg/ic_next.svg
  src/assets/svg/register/ic_grey-circle.svg
  src/assets/svg/register/ic_step1.svg
  src/assets/svg/register/ic_step2.svg
  src/assets/svg/register/ic_step3.svg
  src/assets/svg/register/ic_step4.svg
  src/components/Register/CheckBox.tsx
  src/components/Register/Step1.tsx
  src/constant/index.ts
  src/styles/GlobalStyles.ts
  src/utils/StepIcon.tsx
  yarn.lock
Labels: ✨ feat, size/L

#52 chore: 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feature.yml
  .github/workflows/close_jira_issue.yml
  .github/workflows/create_jira_issue.yml
  .github/workflows/reopen_jira_issue.yml
Labels: size/L, 📦 chore

#55 bugfix: build 에러를 해결합니다.
  src/assets/index.ts
  src/assets/svg/check/ic_check-complete.svg
  src/assets/svg/check/ic_check-grey.svg
  src/assets/svg/check/ic_check-mint.svg
  src/assets/svg/check/ic_check-transparent.svg
  src/assets/svg/check/ic_check-whitegrey.svg
  src/assets/svg/ic_back.svg
  src/assets/svg/ic_next.svg
  src/assets/svg/register/ic_grey-circle.svg
  src/assets/svg/register/ic_step1.svg
  src/assets/svg/register/ic_step2.svg
  src/assets/svg/register/ic_step3.svg
  src/assets/svg/register/ic_step4.svg
Labels: size/M, 🐞 bugfix

#61 chore: deploy.yml에 미사용 Docker 리소스 제거 스크립트를 추가합니다.
  .github/workflows/deploy.yml
Labels: size/XS, 📦 chore

#63 bugfix: 약관동의 페이지 레이아웃 height 계산 오류를 수정합니다.
  src/app/sign-up/layout.css.ts
  src/app/sign-up/layout.tsx
  src/app/sign-up/terms/page.tsx
  src/app/sign-up/terms/terms.css.ts
  src/components/Common/Header/Header.tsx
  src/components/Common/Header/header.css.ts
Labels: size/L, 🐞 bugfix

#64 feat: Pretendard font를 적용합니다 (next/font)
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
  src/styles/global.css.ts
Labels: ✨ feat, size/S

#67 chore: .dockerignore를 추가합니다.
  .dockerignore
Labels: size/M, 📦 chore

#68 feat: 회원가입 2단계 - 이메일 입력 페이지 퍼블리싱
  src/app/sign-up/email/email.css.ts
  src/app/sign-up/email/page.tsx
  src/components/Common/TextField/textField.css.ts
  src/components/SignUp/Email/EmailForm/EmailForm.tsx
  src/components/SignUp/Email/EmailForm/emailForm.css.ts
  src/components/SignUp/Email/SubmitButton/SubmitButton.tsx
  src/components/SignUp/Email/SubmitButton/submitButton.css.ts
Labels: ✨ feat, size/L

#72 fix: StepIcon 컴포넌트 레이아웃을 수정합니다.
  src/app/sign-up/terms/terms.css.ts
  src/components/SignUp/StepIcon/StepIcon.tsx
  src/components/SignUp/StepIcon/stepIcon.css.ts
Labels: size/M, 🛠️ fix

#74 chore: Jira issue 생성 workflow를 제거합니다.
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/workflows/close_jira_issue.yml
  .github/workflows/create_jira_issue.yml
  .github/workflows/reopen_jira_issue.yml
Labels: size/L, 📦 chore

#76 feat: 태블릿 PC 디바이스 반응형에 대응합니다.
  src/styles/global.css.ts
Labels: ✨ feat, size/XS
